apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mxo1wfx43-nodejs 
  janus-idp.io/tekton: mxo1wfx43-nodejs
  backstage.io/kubernetes-id: mxo1wfx43-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mxo1wfx43-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml