apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mxo1wfx43-nodejs
  janus-idp.io/tekton: mxo1wfx43-nodejs
  backstage.io/kubernetes-id: mxo1wfx43-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mxo1wfx43-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
